# Generated by Django 3.2 on 2022-05-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_tables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingstatus',
            name='id',
        ),
        migrations.AddField(
            model_name='bookingstatus',
            name='code',
            field=models.CharField(choices=[('B', 'Booked'), ('F', 'Fulfilled'), ('C', 'Cancelled')], default='B', max_length=1, primary_key=True, serialize=False),
        ),
    ]
