# Generated by Django 3.2 on 2022-05-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_tables', '0003_buffetperiods'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuffetPeriods',
            new_name='BuffetPeriod',
        ),
        migrations.AlterModelOptions(
            name='buffetperiod',
            options={'ordering': ['start_time']},
        ),
        migrations.RenameField(
            model_name='bookingstatus',
            old_name='status',
            new_name='description',
        ),
    ]
