# Generated by Django 3.2 on 2022-05-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_tables', '0004_auto_20220512_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPreference',
            fields=[
                ('code', models.CharField(choices=[('D', 'Duration of each Buffet Service'), ('N', 'No Show Time Duration Minutes'), ('C', 'Cancellation Notice Minutes'), ('P', 'Buffet Price per Person')], default='P', max_length=1, primary_key=True, serialize=False)),
                ('data', models.PositiveIntegerField()),
            ],
        ),
    ]
