# Generated by Django 3.2 on 2022-05-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_tables', '0007_alter_systempreference_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeMessage',
            fields=[
                ('code', models.CharField(choices=[('T', 'Terms of Use'), ('P', 'Privacy Policy')], max_length=1, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
    ]
