# Generated by Django 3.2 on 2022-05-13 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_tables', '0007_alter_systempreference_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.PositiveSmallIntegerField(default=1)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('date_cancelled', models.DateTimeField(blank=True)),
                ('date_fulfilled', models.DateTimeField(blank=True)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_by', to=settings.AUTH_USER_MODEL)),
                ('booked_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_for', to=settings.AUTH_USER_MODEL)),
                ('booking_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_tables.bookingstatus')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_by', to=settings.AUTH_USER_MODEL)),
                ('fulfilled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_by', to=settings.AUTH_USER_MODEL)),
                ('start_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_tables.buffetperiod')),
            ],
            options={
                'ordering': ['-booking_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TablesBooked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general_tables.diningtable')),
            ],
        ),
    ]
