# Generated by Django 3.2 on 2022-05-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seats',
            field=models.PositiveSmallIntegerField(choices=[(1, '1people'), (2, '2people'), (3, '3people'), (4, '4people'), (5, '5people'), (6, '6people'), (7, '7people'), (8, '8people'), (9, '9people'), (10, '10people')], default=1),
        ),
    ]
