# Generated by Django 3.2 on 2022-05-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dinner_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seats',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 people'), (2, '2 people'), (3, '3 people'), (4, '4 people'), (5, '5 people'), (6, '6 people'), (7, '7 people'), (8, '8 people')], default=1),
        ),
    ]
