# Generated by Django 3.2 on 2022-05-13 14:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20220513_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dinner_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 13, 14, 44, 25, 969048, tzinfo=utc)),
        ),
    ]
