# Generated by Django 3.2 on 2022-05-14 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_tables', '0007_alter_systempreference_code'),
        ('bookings', '0006_alter_booking_dinner_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_cancelled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_fulfilled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='general_tables.buffetperiod'),
        ),
    ]
