# Generated by Django 3.2 on 2022-05-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_auto_20220514_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesbooked',
            name='date_booked',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tablesbooked',
            name='seats_booked',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
