# Generated by Django 3.2 on 2022-05-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_tablesbooked_time_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesbooked',
            name='table_capacity',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
