# Generated by Django 3.2 on 2022-05-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_tablesbooked_table_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seats',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
