# Generated by Django 3.2 on 2022-05-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
