# Generated by Django 3.2 on 2022-05-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_booking_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablesbooked',
            name='date_booked',
            field=models.DateField(),
        ),
    ]
