# Generated by Django 3.2 on 2022-05-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
