# Generated by Django 3.2 on 2022-05-13 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('cuisine', '0002_alter_cuisine_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuisineChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
                ('cuisine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuisine.cuisine')),
            ],
        ),
    ]
